%YAML:1.0

# camera intrinsics (for left) mm
camera.fx: 351.24
camera.fy: 351.96
camera.cx: 315.28
camera.cy: 243.18


# feature tracker parameters
FeatureDistance: 10                 # the distance between two keypoints
Frequence: 10                       # the fequence of publish feature tracker
BorderSize: 1                        #
FeatureMinDis: 15                   #
MaxFeatureCnt: 150                   #

F_THRESHOLD: 1.0